theme: jekyll-theme-minimal
title: LAThomson
description: Welcome to my personal website! </br></br> More of me via&#58; <ul><li> ::marker <a href="linkedin.com/in/LAThomson">LinkedIn</a></li><li> ::marker <a href="github.com/LAThomson">GitHub</a></li><li> ::marker <a href="https://scholar.google.com/citations?user=2pPzGroAAAAJ&hl=en">Google Scholar</a></li><li> ::marker Email&#58; louis[at]cbthomson[dot]com</li></ul>

logo: profile_picture.jpg