theme: jekyll-theme-minimal
title: LAThomson
description: Welcome to my personal website! </br></br> More of me via\: <ul><li> ::marker [LinkedIn](linkedin.com/in/LAThomson)</li><li> ::marker [GitHub](github.com/LAThomson)</li><li> ::marker [Google Scholar](https://scholar.google.com/citations?user=2pPzGroAAAAJ&hl=en)</li><li> ::marker Email\: louis\[at\]cbthomson\[dot\]com</li></ul>

logo: profile_picture.jpg